In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt


df = pd.read_csv("../data/treated/heart_treated.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Elderly,max_hr_predicted,hr_ratio,oldpeak_risk
0,40,M,ATA,140,289.0,0,Normal,172,N,0.0,Up,0,False,180,0.955556,low
1,49,F,NAP,160,180.0,0,Normal,156,N,1.0,Flat,1,False,171,0.912281,low
2,37,M,ATA,130,283.0,0,ST,98,N,0.0,Up,0,False,183,0.535519,low
3,48,F,ASY,138,214.0,0,Normal,108,Y,1.5,Flat,1,False,172,0.627907,moderated
4,54,M,NAP,150,195.0,0,Normal,122,N,0.0,Up,0,False,166,0.734940,low

### Standardizing the columns names

In [4]:
df = df.rename(columns=str.lower)

In [5]:
df.dtypes

age                   int64
sex                     str
chestpaintype           str
restingbp             int64
cholesterol         float64
fastingbs             int64
restingecg              str
maxhr                 int64
exerciseangina          str
oldpeak             float64
st_slope                str
heartdisease          int64
elderly                bool
max_hr_predicted      int64
hr_ratio            float64
oldpeak_risk            str
dtype: object

### Categorical variables encoding

In [6]:
df["sex"] = df["sex"].map({"M": 0, "F": 1})

In [7]:
df["exerciseangina"] = df["exerciseangina"].map({"Y": 1, "N": 0})

In [8]:
df = pd.get_dummies(df, columns=["restingecg", "st_slope", "oldpeak_risk", "chestpaintype"], drop_first=True)

In [9]:
df

,age,sex,restingbp,cholesterol,fastingbs,maxhr,exerciseangina,oldpeak,heartdisease,elderly,...,hr_ratio,restingecg_Normal,restingecg_ST,st_slope_Flat,st_slope_Up,oldpeak_risk_low,oldpeak_risk_moderated,chestpaintype_ATA,chestpaintype_NAP,chestpaintype_TA
0,40,0,140,289.0,0,172,0,0.0,0,False,...,0.955556,True,False,False,True,True,False,True,False,False
1,49,1,160,180.0,0,156,0,1.0,1,False,...,0.912281,True,False,True,False,True,False,False,True,False
2,37,0,130,283.0,0,98,0,0.0,0,False,...,0.535519,False,True,False,True,True,False,True,False,False
3,48,1,138,214.0,0,108,1,1.5,1,False,...,0.627907,True,False,True,False,False,True,False,False,False
4,54,0,150,195.0,0,122,0,0.0,0,False,...,0.734940,True,False,False,True,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,110,264.0,0,132,0,1.2,1,False,...,0.754286,True,False,True,False,False,True,False,False,True
914,68,0,144,193.0,1,141,0,3.4,1,True,...,0.927632,True,False,True,False,False,False,False,False,False
915,57,0,130,131.0,0,115,1,1.2,1,False,...,0.705521,True,False,True,False,False,True,False,False,False
916,57,1,130,236.0,0,174,0,0.0,1,False,...,1.067485,False,False,True,False,True,False,True,False,False
917,38,0,138,175.0,0,173,0,0.0,0,False,...,0.950549,True,False,False,True,True,False,False,True,False

In [10]:
df = df.rename(columns=str.lower)

In [11]:
df

,age,sex,restingbp,cholesterol,fastingbs,maxhr,exerciseangina,oldpeak,heartdisease,elderly,...,hr_ratio,restingecg_normal,restingecg_st,st_slope_flat,st_slope_up,oldpeak_risk_low,oldpeak_risk_moderated,chestpaintype_ata,chestpaintype_nap,chestpaintype_ta
0,40,0,140,289.0,0,172,0,0.0,0,False,...,0.955556,True,False,False,True,True,False,True,False,False
1,49,1,160,180.0,0,156,0,1.0,1,False,...,0.912281,True,False,True,False,True,False,False,True,False
2,37,0,130,283.0,0,98,0,0.0,0,False,...,0.535519,False,True,False,True,True,False,True,False,False
3,48,1,138,214.0,0,108,1,1.5,1,False,...,0.627907,True,False,True,False,False,True,False,False,False
4,54,0,150,195.0,0,122,0,0.0,0,False,...,0.734940,True,False,False,True,True,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,0,110,264.0,0,132,0,1.2,1,False,...,0.754286,True,False,True,False,False,True,False,False,True
914,68,0,144,193.0,1,141,0,3.4,1,True,...,0.927632,True,False,True,False,False,False,False,False,False
915,57,0,130,131.0,0,115,1,1.2,1,False,...,0.705521,True,False,True,False,False,True,False,False,False
916,57,1,130,236.0,0,174,0,0.0,1,False,...,1.067485,False,False,True,False,True,False,True,False,False
917,38,0,138,175.0,0,173,0,0.0,0,False,...,0.950549,True,False,False,True,True,False,False,True,False

### Checking for missing values

In [12]:
df.isna().sum()

age                         0
sex                         0
restingbp                   0
cholesterol               172
fastingbs                   0
maxhr                       0
exerciseangina              0
oldpeak                     0
heartdisease                0
elderly                     0
max_hr_predicted            0
hr_ratio                    0
restingecg_normal           0
restingecg_st               0
st_slope_flat               0
st_slope_up                 0
oldpeak_risk_low            0
oldpeak_risk_moderated      0
chestpaintype_ata           0
chestpaintype_nap           0
chestpaintype_ta            0
dtype: int64

In [13]:
df["cholesterol"] = df["cholesterol"].fillna(df["cholesterol"].median())

### Scaling

In [14]:
X = df.drop("heartdisease", axis=1)
y = df["heartdisease"]

X_numeric = ["age", "restingbp", "cholesterol", "maxhr", "oldpeak", "hr_ratio"]

In [15]:
X_cat = [col for col in X.columns if col not in X_numeric]

In [16]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = pd.DataFrame(
    scaler.fit_transform(X[X_numeric]), 
    columns = X_numeric,
    index = X.index
)

In [17]:
### Concatenating the scaled variables (X_scaled) with the categorical ones (X_cat)
X_final = pd.concat([X_scaled, X[X_cat]], axis=1)

### Exporting final dataset

In [18]:
df_final = pd.concat([X_final, y], axis=1)

In [19]:
df_final_csv = df_final.to_csv("../data/treated/df_final.csv", index=False)